# Generated by Django 4.1 on 2022-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('browser', models.CharField(max_length=64, verbose_name='浏览器')),
            ],
        ),
    ]
