# Generated by Django 4.1 on 2022-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuser',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
    ]
